# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build && Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
    SERVER_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # 服务器私钥
    SERVER_HOST: ${{ secrets.SERVER_HOST }} # 服务器IP地址
    USER_NAME: ${{ secrets.SERVER_USER }} # 服务器用户名

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install 
    
    - name: Build
      run: npm run docs:build
      
    - name: ssh deploy
      uses: easingthemes/ssh-deploy@v4.1.8
      with: 
        SSH_PRIVATE_KEY: ${{ env.SERVER_PRIVATE_KEY }}
        REMOTE_HOST: ${{ env.SERVER_HOST }}
        REMOTE_USER: ${{ env.USER_NAME }}
        SOURCE: 'docs/.vuepress/dist/'
        TARGET: '/var/www/moodle/teacher-manual/'
